-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 16:07:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
GRANT ALL ON mydb.* TO user@localhost IDENTIFIED BY 'pass';
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `ID` INT NOT NULL,
  `First name` VARCHAR(45) NOT NULL,
  `Last name` VARCHAR(45) NOT NULL,
  `Company` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Reminder_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Reminder_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Case`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Case` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Case` (
  `ID` INT NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Customer_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Customer_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `ID` INT NOT NULL,
  `First name` VARCHAR(45) NOT NULL,
  `Last name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Action` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Action` (
  `ID` INT NOT NULL,
  `actions` VARCHAR(45) NOT NULL,
  `Employee_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Employee_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Employee` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `ID` INT NOT NULL,
  `First name` VARCHAR(45) NOT NULL,
  `Last name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Action`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Action` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Action` (
  `ID` INT NOT NULL,
  `actions` VARCHAR(45) NOT NULL,
  `Employee_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Employee_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reminder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reminder` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reminder` (
  `ID` INT NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `Action_ID` INT NOT NULL,
  `Action_Employee_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Action_ID`, `Action_Employee_ID`),
  UNIQUE INDEX `idReminder_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (
  `ID` INT NOT NULL,
  `First name` VARCHAR(45) NOT NULL,
  `Last name` VARCHAR(45) NOT NULL,
  `Company` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `Reminder_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `Reminder_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
